"""Add submission_time and qr_scan_time to User model

Revision ID: b7efde345d29
Revises: 581f296621cf
Create Date: 2025-04-02 23:30:39.992193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7efde345d29'
down_revision = '581f296621cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('qr_scan_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('qr_scan_time')
        batch_op.drop_column('submission_time')

    # ### end Alembic commands ###
